spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${app.secure.datasource.url}
    username: ${app.secure.datasource.username}
    password: ${app.secure.datasource.password}
  data:
    redis:
      host: ${app.secure.redis.host}
      port: ${app.secure.redis.port}
      password: ${app.secure.redis.password}
      database: ${app.secure.redis.database}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100
  rabbitmq:
    host: ${app.secure.rabbitmq.host}
    port: ${app.secure.rabbitmq.port}
    virtual-host: ${app.secure.rabbitmq.virtual-host}
    username: ${app.secure.rabbitmq.username}
    password: ${app.secure.rabbitmq.password}
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 1
        max-attempts: 3
      mandatory: true
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000ms
          multiplier: 2.0
          max-interval: 10000ms
  ai:
    deepseek:
      api-key: ${app.secure.ai.deepseek.api-key}
      chat:
      embedding:
        enabled: false
        options:
          model: deepseek-chat
          temperature: 0.3
          max-tokens: 1024
    openai:
      base-url: ${app.secure.ai.openai.base-url}
      api-key: ${app.secure.ai.openai.api-key}
      embedding:
        enabled: true
        options:
          model: text-embedding-v4

    vectorstore:
      qdrant:
        host: ${app.secure.ai.vectorstore.qdrant.host}
        port: ${app.secure.ai.vectorstore.qdrant.port}
        collection-name: vector_store


elasticsearch:
  host: ${app.secure.elasticsearch.host}
  port: ${app.secure.elasticsearch.port}
  scheme: ${app.secure.elasticsearch.scheme}
  connection-timeout: 10s
  socket-timeout: 30s
  connection-request-timeout: 5s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
